-- MySQL Script generated by MySQL Workbench
-- Thu Mar 29 20:09:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `subscriptions` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administrators`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`administrators` ;

CREATE TABLE IF NOT EXISTS `mydb`.`administrators` (
  `idAdministrators` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdministrators`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`catalogpublications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`catalogpublications` ;

CREATE TABLE IF NOT EXISTS `mydb`.`catalogpublications` (
  `idpublications` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `discription` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `administrators_catalogpublications_idpublications` INT NOT NULL,
  `administrators_catalogpublications_price` INT NOT NULL,
  PRIMARY KEY (`idpublications`, `price`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`payment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`payment` (
  `idpayment` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpayment`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`subscription` ;

CREATE TABLE IF NOT EXISTS `mydb`.`subscription` (
  `idsubscription` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `subscriptions` VARCHAR(45) NULL,
  `catalogpublications_idpublications` INT NOT NULL,
  `catalogpublications_price` INT NOT NULL,
  PRIMARY KEY (`idsubscription`),
  INDEX `fk_subscription_catalogpublications1_idx` (`catalogpublications_idpublications` ASC, `catalogpublications_price` ASC),
  CONSTRAINT `fk_subscription_catalogpublications1`
  FOREIGN KEY (`catalogpublications_idpublications` , `catalogpublications_price`)
  REFERENCES `mydb`.`catalogpublications` (`idpublications` , `price`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;